import { useEffect,useState } from 'react';
import api from '../api/axios';
import BudgetAlert from '../components/BudgetAlert';
const CATEGORIES=['Overall','Food','Transport','Shopping','Bills','Entertainment','Health','Groceries','Rent','Education','Other'];
export default function Budget(){const[budgets,setBudgets]=useState([]),[alerts,setAlerts]=useState([]),[form,setForm]=useState({category:'Overall',monthlyLimit:'',alertThresholdPercent:80}),[error,setError]=useState(''),[loading,setLoading]=useState(true);const loadData=async()=>{setLoading(true);try{const[b,a]=await Promise.all([api.get('/budgets'),api.get('/budgets/alerts')]);setBudgets(b.data);setAlerts(a.data)}catch(e){console.error(e)}finally{setLoading(false)}};useEffect(()=>{loadData()},[]);const handleSubmit=async e=>{e.preventDefault();setError('');try{await api.post('/budgets',{...form,monthlyLimit:Number(form.monthlyLimit)});setForm({category:'Overall',monthlyLimit:'',alertThresholdPercent:80});loadData()}catch(e){setError(e.response?.data?.message||'Failed to set budget')}};const handleDelete=async id=>{if(!confirm('Delete this budget?'))return;await api.delete(`/budgets/${id}`);loadData()};if(loading)return <div className="spinner" style={{margin:'80px auto'}}/>;return <div>
  <div className="page-header"><div><h1>Budgets</h1><p>Set guardrails so your spending stays intentional.</p></div></div><BudgetAlert alerts={alerts}/>
  <div className="page-split"><div className="card"><div className="panel-heading"><div><h3>Create a budget</h3><div className="muted">Choose a category and monthly limit.</div></div></div><form onSubmit={handleSubmit}><div className="form-group"><label>Category</label><select value={form.category} onChange={e=>setForm({...form,category:e.target.value})}>{CATEGORIES.map(c=><option key={c}>{c}</option>)}</select></div><div className="form-group"><label>Monthly limit (₹)</label><input type="number" required min="0" value={form.monthlyLimit} onChange={e=>setForm({...form,monthlyLimit:e.target.value})} placeholder="e.g. 5000"/></div><div className="form-group"><label>Alert threshold (%)</label><input type="number" min="1" max="100" value={form.alertThresholdPercent} onChange={e=>setForm({...form,alertThresholdPercent:Number(e.target.value)})}/></div>{error&&<p className="error-text">{error}</p>}<button className="btn btn-primary btn-inline" type="submit">Save budget →</button></form></div>
  <div className="card"><div className="panel-heading"><div><h3>Current budgets</h3><div className="muted">Your active monthly guardrails</div></div></div>{budgets.length===0?<div className="empty-state" style={{minHeight:180}}><div className="empty-icon">◫</div><strong>No budgets yet</strong><span>Create one to start tracking your limits.</span></div>:budgets.map(b=><div className="budget-row" key={b._id}><div className="budget-row-top"><div><strong style={{fontSize:13}}>{b.category}</strong><div className="muted">₹{b.monthlyLimit.toLocaleString('en-IN')} / month · alert at {b.alertThresholdPercent}%</div></div><button className="btn btn-danger btn-sm" onClick={()=>handleDelete(b._id)}>Delete</button></div><div className="progress"><span style={{width:`${Math.min(100,b.alertThresholdPercent)}%`}}/></div></div>)}</div></div>
</div>}
